name: ${project.name}
version: ${project.version}
description: ${project.description}
authors: [${project.authors}]
main: ${project.main}
commands:
  jukeloop:
    usage: /<command> reload
    permission: jukeloop.admin
